# Generated by Django 3.2.3 on 2021-06-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0003_category_historicalcategory_historicalinsta_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalinsta_photo',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinsta_photo',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalCategory',
        ),
        migrations.DeleteModel(
            name='HistoricalInsta_Photo',
        ),
    ]
