# Generated by Django 3.2.3 on 2021-06-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0004_auto_20210601_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
