# Generated by Django 3.2.3 on 2021-06-01 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0007_auto_20210601_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GALLERY.location'),
        ),
    ]
