# Generated by Django 3.2.3 on 2021-06-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0008_alter_photo_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='Location',
        ),
        migrations.AddField(
            model_name='category',
            name='location',
            field=models.ManyToManyField(to='GALLERY.Location'),
        ),
    ]
