# Generated by Django 3.2.3 on 2021-06-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0009_auto_20210602_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='Category',
        ),
    ]
