# Generated by Django 3.2.3 on 2021-06-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0011_auto_20210602_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='thumbnail'),
            preserve_default=False,
        ),
    ]
