# Generated by Django 3.2.3 on 2021-06-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0012_album_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='url_slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
