# Generated by Django 3.2.3 on 2021-06-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0014_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('image', models.ImageField(upload_to='staff')),
                ('post', models.CharField(max_length=50)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
